
project_id = "smlqmythgpkucxbaxuob"

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-polling]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.update-telegram-token]
verify_jwt = false

[functions.bot-api]
verify_jwt = false

[functions.docs]
included_files = [
  "supabase/functions/docs/index.html",
  "supabase/functions/docs/group_collect_api.yaml"
]
verify_jwt = false
