
project_id = "smlqmythgpkucxbaxuob"

[api]
enabled = true

[db]
shadow_database_enabled = false

[realtime]
enabled = true
hostname = "localhost"

[edge_functions]
[edge_functions.setup-telegram-webhook]
[edge_functions.telegram-webhook]
[edge_functions.update-telegram-token]
verify_jwt = true
