openapi: 3.0.0
info:
  title: Group Collect Bot API
  version: 1.0.0
  description: Public API for interaction between Telegram Mini App and Group Collect
    Bot
paths:
  /collections:
    get:
      summary: Get collections for a user
      parameters:
      - name: user_id
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of collections
          content:
            application/json:
              example:
              - id: abcd-1234
                title: "\u041D\u0430 \u043F\u043E\u0434\u0430\u0440\u043E\u043A"
                status: active
                target_amount: 10000
                current_amount: 3000
                deadline: '2025-05-20'
        '400':
          description: Missing or invalid user_id
          content:
            application/json:
              example:
                error: user_id is required
    post:
      summary: Create a new collection
      requestBody:
        required: true
        content:
          application/json:
            example:
              user_id: '12345'
              title: "\u041D\u0430 \u0446\u0432\u0435\u0442\u044B"
              description: "\u0414\u043B\u044F \u0443\u0447\u0438\u0442\u0435\u043B\
                \u044F"
              target_amount: 2000
              deadline: '2025-05-30'
      responses:
        '200':
          description: Collection created
          content:
            application/json:
              example:
                id: uuid
                status: draft
        '422':
          description: Validation failed
          content:
            application/json:
              example:
                error: Invalid date format
  /collections/{id}:
    get:
      summary: Get collection details
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Collection details
          content:
            application/json:
              example:
                id: abcd-1234
                title: "\u041F\u043E\u0434\u0430\u0440\u043E\u043A"
                description: "\u041D\u0430 \u0434\u0435\u043D\u044C \u0440\u043E\u0436\
                  \u0434\u0435\u043D\u0438\u044F"
                target_amount: 10000
                current_amount: 3000
                status: active
                creator_id: '9876543'
                deadline: '2025-05-20'
                payments:
                - user_id: '12345'
                  amount: 1000
                  status: confirmed
                  created_at: '2025-05-01'
        '404':
          description: Collection not found
          content:
            application/json:
              example:
                error: Collection not found
    patch:
      summary: Update collection
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: "\u041E\u0431\u043D\u043E\u0432\u043B\u0451\u043D\u043D\u043E\
                \u0435 \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u0435"
              target_amount: 12000
      responses:
        '200':
          description: Collection updated
          content:
            application/json:
              example:
                status: updated
        '404':
          description: Collection not found
          content:
            application/json:
              example:
                error: Collection not found
