@startuml
' Диаграмма состояний одного сбора

' Устанавливаем стиль отображения
skinparam state {
  BackgroundColor White
  BorderColor Black
  FontSize 12
}

' Начальное состояние
[*] --> Черновик : Команда /new\n(создание пустого сбора)
' Комментарий: Когда пользователь запускает /new, создаётся черновой сбор с chat_id, user_id и датой создания

state Черновик {

  [*] --> ВводНазвания
  ВводНазвания --> ВводОписание : /setname
  ВводОписание --> ВводЦели : /setdescription
  ВводЦели --> ВводДаты : /setamount
  ВводДаты --> ФинальноеПодтверждение : /setdate


state fork_cancel <<fork>>
}
  ' Команда отмены создания (или кнопка "отменить создание")
  ВводНазвания --> fork_cancel : /cancel
  ВводОписание --> fork_cancel : /cancel
  ВводДаты --> fork_cancel : /cancel
  ФинальноеПодтверждение --> fork_cancel : /cancel
  fork_cancel --> Отменён

ФинальноеПодтверждение --> Активен : /approve

state Активен {
[*] --> Оплачен : /paid
note bottom of Оплачен : Это не отдельный статус, \nа наличие хотя бы одной оплаты. \nЗавершить сбор можно и без оплат

[*] --> Дедлайн : завершение периода сбора
note bottom of Дедлайн : Это не отдельный статус, \nа пометка о наступлении дедлайна. \nСтатус сбора - еще "Активен", его \nможно изменить, отменить, заершить
}
' Комментарий: После ввода всех параметров сбор становится активным
Активен --> Завершён : /finish
Активен --> Отменён : /cancel



' Комментарий: Завершённый или отменённый сбор нельзя больше редактировать или оплачивать
Завершён --> [*]
Отменён --> [*]


@enduml
