// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smlqmythgpkucxbaxuob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtbHFteXRoZ3BrdWN4YmF4dW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTMxMjEsImV4cCI6MjA2MTEyOTEyMX0.ns2zOcH6JElPYV-f6MrXEN1sRsIVS6pOWSPzAxAJ2Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);